title: Xiaoyi Gu
logo: img/img1.png
description: "Welcome to Xiaoyi's homepage! \nAttracted by Machine Learning when I was a sophomore in a Data Mining course, I am fighting my way to start a career in this area. \nUsing the known to explore the unknown, like panning for gold in the sand, I believe, is part of data science's charm. \nI'm always hoping to get closer to another intelligent form of the world through modern computer technology. \nTo build my own knowledge kingdom of technology, I will always explore opportunities and never stop learning."
# show_downloads: true
theme: jekyll-theme-minimal
